### ISSUE TITLE
importPaths not working in VS Code on Linux

### ISSUE THREAD

**Issue by Jebbs** [d-language-server/dls#10]
When I add a path to the `d.dls.symbol.importPaths` setting in VS Code, the extension does not seem to use it when finding symbols. This was working until recently (a couple of weeks ago?), but is not working anymore after either a VS Code update or a dls update.

When I move the source code for the package into the `src` of my project, everything works as expected.

**Comment by LaurentTreguier** [comment]
That's certainly because of a dls update and not a VSCode one.
I've touched the import functions a bit lately.

**Comment by LaurentTreguier** [comment]
This should be fixed in v0.12.3

**Comment by Jebbs** [comment]
It works now, thank you!
