### ISSUE TITLE
Can't Go to Declaration for Local Module

### ISSUE THREAD

**Issue by look-at-me** [d-language-server/dls#19]
Try to go into "one/a.d" put the cursor somewhere inside "BType" and press F12 (for vscode). It won't find be able to find the symbol. Goto definition works for the std library. Checked the ModuleCache and the two files are in it. Was working in an older version, not sure when it stopped.

[test.zip](https://github.com/d-language-server/dls/files/2717498/test.zip)

**Comment by LaurentTreguier** [comment]
Ah, managed to reproduce it when the folder isn't directly opened, but added to a workspace. I think it's because I'm not handling relative paths, and expecting absolute ones only.

**Comment by look-at-me** [comment]
Was on windows, I had the golder open with vscode. I did try both relative and absolute paths but the problem still persisted. I also added some debug logging and the files were being added to the module cache correctly. 

I'm using the insiders version of vscode, not sure if that would make a difference. I'll try a few different things when I get home.

**Comment by LaurentTreguier** [comment]
If the problem is still there, maybe the next minor version, with the latest DCD and dsymbol, could fix it. I'll probably release it tomorrow.

**Comment by look-at-me** [comment]
Alright I updated DLS to use DCD 0.10.2 and seems to be working with an absolute path at least.

**Comment by LaurentTreguier** [comment]
With DLS v0.21.0 it should use DCD v0.10.2, and automatically convert relative paths to absolute ones.

**Comment by look-at-me** [comment]
Sweet, thanks pushing it out so quickly!
