### ISSUE TITLE
Can't Go to Declaration for Local Module

### ISSUE THREAD

**Issue by look-at-me** [d-language-server/dls#24]
Still have the issue. It worked at least once when I tried it but can't get it to work anymore. I uploaded a different project configuration if you want to see if you can reproduce it. It works fine if the "Core" folder is in the workspace directory. But otherwise it doesn't work. Full module imports work as well, but not package.d imports that do public imports eg `import Core`. Tested with DCD and it works fine there.

[dlserror.zip](https://github.com/d-language-server/dls/files/2766214/dlserror.zip)

![img](https://user-images.githubusercontent.com/42397654/51281257-de3cab80-19af-11e9-91f5-ebef2ed945a4.gif)

![img2](https://user-images.githubusercontent.com/42397654/51281555-c154a800-19b0-11e9-8ec7-93b047330be5.gif)

**Comment by LaurentTreguier** [comment]
This is caused by the fact that you are manually importing a folder inside another folder that's already imported (the current directory is automatically imported).

**Comment by look-at-me** [comment]
Can you add an option to disable importing the workspace and probably submodules too. I'd just want the D standard library to be automatically imported and then manually specify which folders to use as import paths.

**Comment by LaurentTreguier** [comment]
I've added a `d.init.symbol.autoImports` option to disable automatic imports in v0.21.10

**Comment by look-at-me** [comment]
Perfect, it definitely works now lol. Thanks!
