### ISSUE TITLE
Connection to server is erroring. Shutting down server.

### ISSUE THREAD

**Issue by artemirq** [d-language-server/dls#25]
![image](https://user-images.githubusercontent.com/17342159/52593228-79af2800-2e59-11e9-8f0c-384791e77dbe.png)

```
import std.stdio;

void main() {
    string[] arrayOfString = ['""'];
}
```

### Stacktrace [LOG](https://pastebin.com/q5EjYfuR)

**Comment by LaurentTreguier** [comment]
It doesn't crash with this code for me.
- Have you changed `vscode-dlang`'s configuration ?
- Does the server crash with only this code ?
- Can you run DFMT on the code (`dub fetch dfmt; dub run dfmt -- vscode-dlang-test.d`) ?

**Comment by LaurentTreguier** [comment]
Nevermind, I managed to reproduce it.
Until I fix it, you can set `d.init.catchError` to `true` in VSCode to ignore the errors.
