### ISSUE TITLE
dub run dls:bootstrap outputs invalid path

### ISSUE THREAD

**Issue by andre2007** [d-language-server/dls#27]
Running ```dub run dls:bootstrap``` outputs path
```C:\Users\User\AppData\Local\dub\packages\.bin\dls-latest\dls.exe```

Folder .bin contains a shortcut with name ```dls-latest```, clicking on this
shortcut shows an error about an invalid path.

**Comment by LaurentTreguier** [comment]
Is there no other folder in the same directory as the `dls-latest` shortcut ?

**Comment by andre2007** [comment]
Exactly, only the shortcut dls-latest exists in this folder.

**Comment by LaurentTreguier** [comment]
That's perplexing, I don't seem to have this problem.
What's the output of `dub run dls:bootstrap -- --check --method=download` ?
If the result if `true`, what's the output of `dub run dls:bootstrap -- --progress` ?

**Comment by andre2007** [comment]
Output for ```dub run dls:bootstrap -- --check --method=download``` was true.

Output for ```dub run dls:bootstrap -- --progress``` was 

```
1766874
233806
1610086
1766874
extract
C:\Users\User\AppData\Local\dub\packages\.bin\dls-latest\dls.exe
```

and now also there is a folder dls-v0.21.12 and the shortcut points to this folder.
I also tried to reproduce this issue by deleting all dub packages but can't
reproduce the issue.
I think we can close this issue. 

PS. I like your idea with the .bin folder. This is something we should add to Dub as generic
functionality.

**Comment by LaurentTreguier** [comment]
I guess it's going to stay a mystery... Either there was a connection problem with Github (although https://githubstatus.com says there hasn't been any problem for the last 5 days), or Windows just said "Nah".

The `.bin` folder is something you can find in NodeJS's `node_modules` folder, maybe it could be helpful to have something similar with Dub that you can put in the `PATH` environment variable.
