### ISSUE TITLE
Dscanner.ini not being used

### ISSUE THREAD

**Issue by look-at-me** [d-language-server/dls#30]
The returned `workspaceUri` appears to always be null, so it will always use the default configuration. Appears to reply on `_workspaceDependencies` which doesn't appear to be set if auto imports is disabled.

https://github.com/d-language-server/dls/blob/master/source/dls/tools/symbol_tool/internal/symbol_tool.d#L584
https://github.com/d-language-server/dls/blob/v0.22.1/source/dls/tools/analysis_tool.d#L358
```D
        const workspaceUri = SymbolTool.instance.getWorkspace(uri);
        immutable workspacePath = workspaceUri is null ? "" : workspaceUri.path;
        return (workspacePath in _analysisConfigs) ? _analysisConfigs[workspacePath]
            : defaultStaticAnalysisConfig();
```

**Comment by LaurentTreguier** [comment]
I added a variable that is actually meant to keep track of open workspaces instead of somewhat misusing another; it should be fixed in v0.22.2.
