### ISSUE TITLE
Static Analysis with No Auto Import

### ISSUE THREAD

**Issue by look-at-me** [d-language-server/dls#35]
Currently when using No Auto Import configuration, the static analysis done with dscanner will only be done with any open files. Would there be a way to set the path or pattern so that the static analysis is done for the specified files as well? I was having problems where, as part of the Android build files with the extensions '.d' were being generated and would have thousands of errors when dscanner processed them as they aren't actually D source files.

**Comment by LaurentTreguier** [comment]
I first thought about using manual imports,  but I guess if you have D files mixed with non-D file with the same extension, using a pattern makes sense.

**Comment by LaurentTreguier** [comment]
What sort of patterns do you need ? With [std.path.globMatch](https://dlang.org/phobos/std_path.html#.globMatch) I can easily support things like `{a,b}/*.d` relative to the current workspace for example

**Comment by look-at-me** [comment]
I guess that glob would work, possible include in the plugin comment of how it works as I think that is a bit different than the usual vscode glob syntax. The `*` only matches a segment of the path in vscode.
