### ISSUE TITLE
Don't Focus Output on Errors

### ISSUE THREAD

**Issue by look-at-me** [d-language-server/dls#36]
It is really annoying when trying to do something in a terminal and something crashes and the focus is stolen away from whatever it is you were doing.  If something goes wrong and it isn't working, then I can go look at the logs manually if I need to.

**Comment by LaurentTreguier** [comment]
DLS doesn't control any focus, so this is probably an issue with the editor you're using. (Although I could still try to make it crash less to reduce the issue)

**Comment by andre2007** [comment]
@look-at-me if you talk about IntelliJ and the LSP plugin I expect the modal dialog to disappear with 1.6.0 
https://github.com/gtache/intellij-lsp/issues/65

**Comment by look-at-me** [comment]
It was for VS Code, I'll make a issue in that repo instead. The error doesn't seem to be happening anymore, so I'll close this.
