### ISSUE TITLE
Internal Error with latest 1.15.8 update

### ISSUE THREAD

**Issue by RUSshy** [d-language-server/dls#38]
Hi

I just installed the latest 1.15.8 update released few moment ago but now dls can't start, i get an "internal error"

```
[Error - 6:19:30 PM] Server initialization failed.
  Message: Internal error
  Code: -32603 
object.Exception@C:\Users\appveyor\AppData\Local\dub\packages\dub-1.14.0\dub\source\dub\packagemanager.d(247): Sub package "sandbox:sandbox" doesn't exist.
----------------
```
My project in case you want to test: https://github.com/RUSshy/game_d

It worked fine with previous update

**Comment by LaurentTreguier** [comment]
From what I tested, the problem starts with https://github.com/RUSshy/game_d/commit/07932914a15cd52f9439095dbd174b86b5c19336; this commit will make DLS crash regardless of its version or vscode-dlang's version.
It still shouldn't be crashing however, so I'll investigate more on this

**Comment by LaurentTreguier** [comment]
Fixed with 8770fadbff4567bc7a3baebdd9a561ade7391689

**Comment by RUSshy** [comment]
I grabbed the latest artifact from AppVeyor and manually replaced it, now it works fine, thanks :)

**Comment by LaurentTreguier** [comment]
You're welcome. But did you need to take it from AppVeyor ? I released v0.23.1 right afterwards; is there a problem with the update system ?

**Comment by RUSshy** [comment]
VSCode didn't ask me to update the extention, and i don't know if there is a way to force check

The website also shows the same version https://marketplace.visualstudio.com/items?itemName=LaurentTreguier.vscode-dls

**Comment by LaurentTreguier** [comment]
I was talking about DLS; not vscode-dlang. The DLS binary is upposed to automatically update itself independently of the VSCode extension

**Comment by RUSshy** [comment]
Oops i missed this notification about your reply

Hmm, i am not really sure, maybe i didn't pay enough attention, does it display a notification ?

**Comment by LaurentTreguier** [comment]
It should; it's supposed to say `DLS upgraded to version v0.23.1`. What's inside your `C:\Users\[your username]\AppData\Local\dub\packages\.bin` folder ?

**Comment by RUSshy** [comment]
![image](https://user-images.githubusercontent.com/18348637/53891694-30529280-402b-11e9-9966-3b67e242bf73.png)

**Comment by RUSshy** [comment]
I removed both folders, and i started vscode now:

![image](https://user-images.githubusercontent.com/18348637/53891818-6db72000-402b-11e9-8e88-7569b16a87f1.png)

**Comment by LaurentTreguier** [comment]
It's still suspicious. It's supposed to be updating automatically. Do you mind if I ping you when I release the next version, to see if it still refuses to update ?

**Comment by RUSshy** [comment]
Sure ! i am glad if i can help, i love DLS it made me come back to D because it makes editing/learning so much better, so thanks a lot !! :)

**Comment by LaurentTreguier** [comment]
Great :smile: 
You haven't changed `d.init.autoUpdate` or `d.init.preReleaseBuilds`, by any chance ? `autoUpdate` is supposed to show a notification before updating, and maybe `preReleaseBuilds` is bugged and refuses to download non-prerelease builds when activated

**Comment by LaurentTreguier** [comment]
When you said you grabbed the latest appveyor artifact, which one exactly did you pick ?

**Comment by RUSshy** [comment]
No i haven't changed DLS settings

I checked in my history, and the link for the artifact i downloaded is:

https://appveyorcidata.blob.core.windows.net/dlanguageserver-104295/dls/625-master/h8jdjnxjcbh3eth1/dls-untagged.windows.x86_64.zip?sv=2015-12-11&sr=c&sig=ffS9fk4gw3NAA36BrsMM5IzJXG4WWTKfr0JCpNOujCs%3D&st=2019-03-04T19%3A57%3A16Z&se=2019-03-04T20%3A03%3A16Z&sp=r

**Comment by RUSshy** [comment]
I did an experiment:

![image](https://user-images.githubusercontent.com/18348637/53893588-c5a35600-402e-11e9-909e-125a478ca946.png)

I put an old version and it didn't download latest version

But that's maybe because i didn't make it a symlink ?

**Comment by LaurentTreguier** [comment]
What you had taken is a debug build, as only releases are built with `dub build --build=release`. These debug builds don't update themselves.
Are you sure it didn't do anything ? If the symlink wasn't changed, then VSCode shoudln't be able to find `dls.exe` and should try to reinstall it.

**Comment by RUSshy** [comment]
Oh ok !

Well maybe last time i didn't wait enough, we'll see when you push new version if it updates, right now i will reinstall vscode to make sure it is a fresh one

**Comment by RUSshy** [comment]
I see you updated DLS, but vscode didn't update it :/

**Comment by LaurentTreguier** [comment]
That's normal, it's a prerelease.

**Comment by LaurentTreguier** [comment]
It's also not been a full hour; DLS will wait until a release is at least an hour old before downloading it, this allows me to remove a faulty release in case something is wrong before anyone downloads it.
I intend to put versions x.x.0 as prerelease from now on to test them further before doinf the full release.

**Comment by RUSshy** [comment]
Ahh ok !!

Let me know when you want me to check :)

**Comment by LaurentTreguier** [comment]
I pulled it out of prerelease mode, as it's bugged and doesn't work... It seems to be updating fine for me.

**Comment by RUSshy** [comment]
Yes it did the update :)

Thanks !!
