### ISSUE TITLE
New release information again and again

### ISSUE THREAD

**Issue by andre2007** [d-language-server/dls#47]
When a new DLS version is available, DLS is automatically updated and I get the information in a popup in IntelliJ. The issue is, this dialog is not shown once, but again and again. Maybe related to when DLS or the LSP plugin crashes. 
Is this issue related to DLS or should I file an issue for LSP plugin (IntelliJ)?

**Comment by LaurentTreguier** [comment]
I don't have this issue using VSCode.
Do you have a path to DLS set manually somewhere ? If so, the same old binary will always be launched instead of the new one.
Or maybe you're just flooded with actual new versions because there have been 4 patch releases within 4 days

**Comment by andre2007** [comment]
You were right, I specified manually a DLS executable instead of the ./bin/ latest executable.
Thanks
