### ISSUE TITLE
Sublime Text - Private field are displayed in completion popup

### ISSUE THREAD

**Issue by RUSshy** [d-language-server/dls#52]
As you can see here, private fields are displayed

![image](https://user-images.githubusercontent.com/18348637/59604497-a8415600-910c-11e9-97e5-82f3cbed47af.png)

**Comment by RUSshy** [comment]
Also, everything is sorted A-Z, just like VSCode, maybe data could be sorted before sent to LSP or what ever it is ? #51

**Comment by RUSshy** [comment]
Issue is mostly in sublime plugin since it works fine with vscode, so i opened an issue there: https://github.com/tomv564/LSP/issues/616

**Comment by LaurentTreguier** [comment]
This is a problem in DCD; however this issue has been fixed (https://github.com/dlang-community/DCD/pull/598), so it's now only a matter of DCD v0.12 being released.
