### ISSUE TITLE
Keywords missing for builtin arrays

### ISSUE THREAD

**Issue by RUSshy** [d-language-server/dls#53]
With regular arrays, there is no way to get completion for keywords like: ``back`` ``popBack()`` ``empty`` etc

I think it would be a good idea to hardcode them ? i always need to recheck doc to know what's available for builtin arrays and right syntax, it is annoying

EDIT: functions from https://dlang.org/library/std/range/primitives/pop_back.html
So no need to hardcode.. i'm stupid

What is the reason such functions aren't detected ? issue with DCD ?

**Comment by RUSshy** [comment]
Hmm i think i mis-read the doc..

**Comment by LaurentTreguier** [comment]
This is because they are not methods of arrays, but simply functions. Doing `myArray.popBack()` uses [UFCS](https://dlang.org/spec/function.html#pseudo-member), which isn't supported by DCD. If I'm not mistaken, that's just because it's hard to properly implement.

**Comment by RUSshy** [comment]
Ah thanks! so this can be closed
