### ISSUE TITLE
DLS dscanner.ini dosen't reflect.

### ISSUE THREAD

**Issue by Gaia0514** [d-language-server/dls#54]
I use DLS on neovim.
I want to disable undocumented declaration
how to apply dscanner.ini to DLS ??

**Comment by Gaia0514** [comment]
sorry. I make mistake.
how to apply dscanner.ini to dls ??

**Comment by LaurentTreguier** [comment]
Normally, DLS uses `dscanner.ini` if it is at the root of the project.
In fact, DLS uses `dscanner.ini` exactly to disable undocumented declaration warnings: https://github.com/d-language-server/dls/blob/master/dscanner.ini.
If you put `dscanner.ini` at the root of your workspace, DLS should read it and apply it.

**Comment by Gaia0514** [comment]
what do you mean of "root of the project" or "root of your workspace"??
I think you mean root isn't root user.
you mean root of DLS project?
I put `~/.dub/packages/dls-0.25.13/dls/dscanner.ini`
but It doesn't work.

**Comment by LaurentTreguier** [comment]
What I mean is this:
When you use DLS, you probably open a folder in Neovim (`nvim my/project/folder/path`).
`dscanner.ini` should then be inside `my/project/folder/path`.
If you use Neovim on separate D files (`nvim some_source_file.d`), you can't use any dscanner.ini file with DLS.

**Comment by Gaia0514** [comment]
oh!! I see!!
Thank you so much.
`dscanner.ini` work!!

**Comment by Gaia0514** [comment]
hmmmm....
I think it is so tired to put always `dscanner.ini` file to each directory.
How about changing this system?

**Comment by LaurentTreguier** [comment]
D-Scanner has a [global configuration file](https://github.com/dlang-community/D-Scanner#configuration-1). I'll try to use this file too; then `$HOME/.config/dscanner/dscanner.ini` should apply to any project.

**Comment by Gaia0514** [comment]
ok! Thank you.
