### ISSUE TITLE
No info for top level functions

### ISSUE THREAD

**Issue by RUSshy** [d-language-server/dls#58]
In this file: https://github.com/ryuukk/arc_d/blob/master/arc/source/arc/gfx/model_loader.d#L24

Code is valid but DLS doesn't know about it:

![image](https://user-images.githubusercontent.com/18348637/62129766-cc7d7e80-b2d7-11e9-9730-7065b5d5e05e.png)

![image](https://user-images.githubusercontent.com/18348637/62129781-d7381380-b2d7-11e9-8e29-5385e27a9cf0.png)

**Comment by LaurentTreguier** [comment]
This is because the module name `arc.gfx.modelloader` differs from the file name `arc/gfx/model_loader.d`. This is more an issue with DCD than with DLS, as I'm not doing anything like module name resolving in DLS's code.

**Comment by RUSshy** [comment]
Oh you are right, once i rename to module name to match filename, it then works fine!
