### ISSUE TITLE
dls server start error?

### ISSUE THREAD

**Issue by xywf221** [d-language-server/dls#61]
vscode display : Connection to server is erroring. Shutting down server.

**Comment by xywf221** [comment]
using `dub init hello` created project iIt's normal.

**Comment by xywf221** [comment]
I used 'vscode' to open a D file directly

**Comment by LaurentTreguier** [comment]
Ok. I'll try to explore this more when I get back on my machine

**Comment by LaurentTreguier** [comment]
Opening a file without a workspace should be fixed with version 0.25.17.
It will be available within about a hour
