### ISSUE TITLE
DLS crashing 

### ISSUE THREAD

**Issue by aldocd4** [d-language-server/dls#65]
Hello, 

Thanks for dls and the vscode extension, it's awesome.  

I have a project ([evael](https://github.com/evael-dev/evael/tree/master/source/evael)) where dlsseems to crash with the following error in DLS console : 
Connection to server is erroring. Shutting down server.

I really don't know how to fx this myself. Can you give us tips to debug this kind of crashes ?

I'm on Windows 10.
Thanks.

**Comment by LaurentTreguier** [comment]
I have no clue why this is happening, but apparently the update check makes DLS crash. I haven't touched the update system in ages and it has worked fine for months, it looks like it just broke itself without any intervention. I've switched the new v0.25.18 to pre-release so the problem should stop for now

**Comment by LaurentTreguier** [comment]
The macOS crash is a completely different issue; yours is a lot easier to pinpoint. D-Scanner crashes when I send it empty modules; so I simply have to check if modules are empty before sending them to D-Scanner.
